[project]
name = "rag-healthinsurance-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.5",
    "langchain-pymupdf4llm>=1.28.0",
    "pymupdf4llm>=1.28.0",
]
